# Generated by Django 4.0.1 on 2022-02-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_todolist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='username',
            new_name='user',
        ),
    ]
